- id: check-const-translations
  name: Check const translation calls.
  description: Check for non-const translation calls.
  entry: check-const-translations
  language: python
  types: [python]
- id: forbid-import
  name: Forbid import.
  description: Forbid imports of specified modules.
  entry: forbid-import
  language: python
  types: [python]
